### ISSUE TITLE
Build issues on Linux

### ISSUE THREAD

**Issue by lgessler** [kawu/contemplata#138]
I attempted to build contemplata on Linux recently and while I was able to succeed eventually I ran into some problems. I'm not a Haskell or Elm expert so maybe some of these are easily averted, but I'd like to document them here so others can benefit if they run into similar problems.

# Backend
- In `src/backend/stack.yaml`, set `resolver` to `lts-10.0`, and set `allow-newer: true`
- `stack install proto-lens-protoc`
- Compile the `.proto` files manually: ```protoc --plugin=protoc-gen-haskell=`which proto-lens-protoc` --haskell_out=src src/Contemplata/Parser/Stanford/CoreNLP.proto```
- In `src/backend`, move `src/Proto/Src/Contemplata` to `src/Proto/Contemplata` 
- In `Proto/Contemplata/Parser/Stanford/CoreNLP.hs`, replace all `Proto.Src` with `Proto`

# Frontend
- Download the appropriate Elm 0.18 binary from [this archive](https://github.com/lydell/elm-old-binaries/releases/tag/main)
- Install executables manually in `~/.config/yarn/global/node/.bin/` (or wherever you like)
- Run `elm` to fetch dependencies
- Proceed to make as directed in README.md

**Comment by lgessler** [comment]
Oh, I see now that `buildProtos = False` by default, not `buildProtos = True` as the readme says. Checking that does solve all of the backend issue 🤦

**Comment by kawu** [comment]
Thanks @lgessler for additional documentation!

My bad regarding `buildProtos = False` by default, it should be set to `True` just as the README suggests.  I will fix that.  I supposed it got switched sometime during development (once you get things working it's more convenient to set it to `False` iirc).

**Comment by lgessler** [comment]
Thanks! I'll close this since there's not much to be done about the Elm bit
